all:
	podman build -q -t powateam/powa-pyutils powa-pyutils/
	podman build -q -t powateam/powa-pgbin powa-pgbin/
	podman build -q -t powateam/powa-pgbench powa-pgbench/
	podman build -q -t powateam/powa-web-dev powa-web-dev/
	podman build -q -t powateam/powa-collector-dev powa-collector-dev/
