all:
	docker build -q -t powateam/powa-pyutils powa-pyutils/
	docker build -q -t powateam/powa-pgbin powa-pgbin/
	docker build -q -t powateam/powa-pgbench powa-pgbench/
	docker build -q -t powateam/powa-web-dev powa-web-dev/
	docker build -q -t powateam/powa-collector-dev powa-collector-dev/
