version: "3"

services:
  powa-repository:
    image: powateam/powa-archivist-git
    container_name: powa-dev-repository
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'
      POWA_EXTRA_SQL: >
        SELECT powa_register_server(hostname => 'powa-dev-remote-primary',
          alias => 'primary',
          username => 'postgres',
          port => 5433,
          frequency => 15,
          extensions => '{pg_stat_kcache,pg_qualstats,pg_wait_sampling,pg_track_settings}');
        SELECT powa_register_server(hostname => 'powa-dev-remote-standby',
          alias => 'standby',
          username => 'postgres',
          port => 5434,
          frequency => 15,
          extensions => '{pg_stat_kcache,pg_qualstats,pg_wait_sampling,pg_track_settings}');
    healthcheck:
      test: ["CMD-SHELL", "psql -U postgres -AXtc 'SELECT count(*) FROM powa_servers' powa | grep 3"]

  powa-collector:
    image: powateam/powa-collector-dev
    container_name: powa-dev-collector
    restart: on-failure
    command: "python3 powa-collector-dev/powa-collector.py"
    volumes:
      - '${POWA_COLLECTOR_GIT}:/usr/local/src/powa-collector-dev'
    depends_on:
      powa-repository:
        condition: service_healthy
      remote-primary:
        condition: service_healthy
      remote-standby:
        condition: service_healthy

  powa-web-dev:
    image: powateam/powa-web-dev
    container_name: powa-dev-web
    command: "python3 powa-web-dev/run_powa.py"
    ports:
      - 8888:8888
    volumes:
      - '${POWA_WEB_GIT}:/usr/local/src/powa-web-dev'
    depends_on:
      powa-repository:
        condition: service_healthy

  remote-primary:
    image: powateam/powa-archivist-git
    container_name: powa-dev-remote-primary
    environment:
      PGPORT: 5433
      POSTGRES_HOST_AUTH_METHOD: 'trust'
      POWA_ROLE: 'PRIMARY'
      POWA_LOCAL_SNAPSHOT: 'NO'
    healthcheck:
      test: ["CMD-SHELL", "psql -U postgres -AXtc 'SELECT count(*) FROM powa_servers' powa"]

  remote-standby:
    image: powateam/powa-archivist-git
    container_name: powa-dev-remote-standby
    environment:
      PGPORT: 5434
      POSTGRES_HOST_AUTH_METHOD: 'trust'
      POWA_ROLE: 'STANDBY'
      POWA_PRIMARY: 'remote-primary'
      POWA_PRIMARY_PORT: '5433'
      POWA_LOCAL_SNAPSHOT: 'NO'
    depends_on:
      remote-primary:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "psql -U postgres -AXtc 'SELECT count(*) FROM powa_servers' powa"]

  pgbench-std-primary:
    image: powateam/powa-pgbench
    container_name: powa-dev-pgbench-std-primary
    restart: on-failure
    environment:
      PGHOST: 'remote-primary'
      PGUSER: 'postgres'
      PGPORT: 5433
      BENCH_SCALE_FACTOR: 10
      BENCH_TIME: 60
      BENCH_FLAG: '-c1 -j1 -n -R 10'
    depends_on:
      remote-primary:
        condition: service_healthy

  pgbench-std-standby:
    image: powateam/powa-pgbench
    container_name: powa-dev-pgbench-std-standby
    restart: on-failure
    environment:
      PGHOST: 'remote-standby'
      PGUSER: 'postgres'
      PGPORT: 5434
      BENCH_SKIP_INIT: 'true'
      BENCH_SCALE_FACTOR: 10
      BENCH_TIME: 120
      BENCH_FLAG: '-c2 -j2 -S -n -R 10'
    depends_on:
      remote-standby:
        condition: service_healthy

  pgdemoworload-std-primary:
    image: powateam/powa-demoworkload
    container_name: powa-dev-demoworkload-std-primary
    restart: on-failure
    environment:
      PGHOST: 'remote-primary'
      PGUSER: 'postgres'
      PGPORT: 5433
    depends_on:
      remote-primary:
        condition: service_healthy
