#vim:set ft=dockerfile
FROM python:3.11-slim
MAINTAINER Julien Rouhaud <rjuju123@gmail.com>

WORKDIR /usr/local/src

RUN apt-get update && apt-get install -y \
    libpq5 \
    libpq-dev \
    git \
    && git clone https://github.com/powa-team/powa-collector.git powa-collector.git \
    && pip install psycopg2-binary \
    && apt-get purge -y --auto-remove libpq-dev git \
    && rm -rf /var/lib/apt/lists/*

COPY powa-collector.conf /etc/

CMD ["python3", "powa-collector.git/powa-collector.py"]
