version: "3"

services:
  powa-repository:
    image: powateam/powa-archivist-git
    container_name: powa-git-repository
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'
      POWA_EXTRA_SQL: >
        SELECT powa_register_server(hostname => 'powa-git-remote-primary',
          alias => 'primary',
          username => 'postgres',
          port => 5433,
          frequency => 15,
          extensions => '{pg_stat_kcache,pg_qualstats,pg_wait_sampling,pg_track_settings}');
        SELECT powa_register_server(hostname => 'powa-git-remote-standby',
          alias => 'standby',
          username => 'postgres',
          port => 5434,
          frequency => 15,
          extensions => '{pg_stat_kcache,pg_qualstats,pg_wait_sampling,pg_track_settings}');
    healthcheck:
      test: ["CMD-SHELL", "psql -U postgres -AXtc 'SELECT count(*) FROM powa_servers' powa | grep 3"]

  powa-collector:
    image: powateam/powa-collector-git
    container_name: powa-git-collector
    restart: on-failure
    depends_on:
      powa-repository:
        condition: service_healthy
      remote-primary:
        condition: service_healthy
      remote-standby:
        condition: service_healthy

  powa-web-git:
    image: powateam/powa-web-git
    container_name: powa-git-web
    ports:
      - 8888:8888

  remote-primary:
    image: powateam/powa-archivist-git
    container_name: powa-git-remote-primary
    environment:
      PGPORT: 5433
      POSTGRES_HOST_AUTH_METHOD: 'trust'
      POWA_ROLE: 'PRIMARY'
      POWA_LOCAL_SNAPSHOT: 'NO'
    healthcheck:
      test: ["CMD-SHELL", "psql -U postgres -AXtc 'SELECT count(*) FROM powa_servers' powa"]

  remote-standby:
    image: powateam/powa-archivist-git
    container_name: powa-git-remote-standby
    environment:
      PGPORT: 5434
      POSTGRES_HOST_AUTH_METHOD: 'trust'
      POWA_ROLE: 'STANDBY'
      POWA_PRIMARY: 'remote-primary'
      POWA_PRIMARY_PORT: '5433'
      POWA_LOCAL_SNAPSHOT: 'NO'
    restart: on-failure
    depends_on:
      remote-primary:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "psql -U postgres -AXtc 'SELECT count(*) FROM powa_servers' powa"]
