#vim:set ft=dockerfile
FROM debian:stable-slim
MAINTAINER Julien Rouhaud <rjuju123@gmail.com>

WORKDIR /usr/local/src

RUN apt-get update && apt-get install -y \
    libpq5 \
    libpq-dev \
    python3 \
    python3-dev \
    python3-pip \
    && pip3 install "sqlalchemy<2.0.0" \
    && pip3 install powa-web \
    && apt-get purge -y --auto-remove libpq-dev python3-dev python3-pip \
    && rm -rf /var/lib/apt/lists/*

COPY powa-web.conf /etc/

EXPOSE 8888
CMD ["powa-web"]
